"""Regenerate paper figures from committed results CSVs.

Closes the deferred Agent 09 task "Ensure every figure can be
regenerated by script". Currently produces:

* ``figures/backtest_equity_curves.png`` -- the leakage-safe
  economic backtest after realistic costs (Agent 09 main-set
  figure #4: "Economic backtest after costs").

Additional paper figures are produced by the legacy notebook
in ``final_notebook/`` and remain there until they need to be
re-generated; this script is the canonical entry point for
any figure derived from ``results/`` artefacts.

Usage::

    python scripts/make_paper_figures.py

The script is deterministic given the committed CSVs.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

REPO = Path(__file__).resolve().parents[1]
RESULTS = REPO / "results"
FIGURES = REPO / "figures"


def make_backtest_equity_figure(out_path: Path, *, cost_bps: float = 10.0,
                                strategy: str = "sign") -> Path:
    """Three-panel net-equity figure (h=1, 5, 15) at fixed costs.

    Each panel overlays the three model strategies plus a buy-and-
    hold benchmark drawn from the same OOF window.
    """
    eq = pd.read_csv(RESULTS / "backtest_equity.csv")
    metrics = pd.read_csv(RESULTS / "backtest_metrics.csv")

    eq["entry_date"] = pd.to_datetime(eq["entry_date"], errors="coerce")
    eq["exit_date"] = pd.to_datetime(eq["exit_date"], errors="coerce")

    sel = eq[(eq["cost_bps"] == cost_bps) & (eq["strategy"] == strategy)
             & (eq["ticker"] == "AAPL")].copy()
    if sel.empty:
        raise RuntimeError(
            f"no backtest_equity rows at cost_bps={cost_bps}, "
            f"strategy={strategy} for AAPL")

    horizons = sorted(sel["horizon"].unique())
    models = sorted(sel["model"].unique())

    fig, axes = plt.subplots(1, len(horizons), figsize=(13, 4.2),
                             sharey=False)
    if len(horizons) == 1:
        axes = [axes]

    bh_cache: dict[int, pd.DataFrame] = {}

    for ax, h in zip(axes, horizons):
        for m in models:
            sub = sel[(sel["horizon"] == h) & (sel["model"] == m)]
            if sub.empty:
                continue
            sub = sub.sort_values("exit_date")
            ax.plot(sub["exit_date"], sub["net_equity"], label=m,
                    linewidth=1.6)

        # Buy-and-hold benchmark: synthesise a daily curve from the
        # ann return reported in metrics (constant compounding over
        # the OOF window). We use the metrics row's
        # buy_and_hold_total_return to anchor the endpoint.
        m0 = metrics[(metrics["horizon"] == h)
                     & (metrics["cost_bps"] == cost_bps)
                     & (metrics["strategy"] == strategy)
                     & (metrics["ticker"] == "AAPL")]
        if not m0.empty:
            row = m0.iloc[0]
            bh_total = float(row["buy_and_hold_total_return"])
            # Anchor B&H to the same trading dates as the strategy
            dates = sel[(sel["horizon"] == h) & (sel["model"] == models[0])
                        ].sort_values("exit_date")["exit_date"]
            if len(dates) >= 2:
                t0, t1 = dates.iloc[0], dates.iloc[-1]
                # Compounded daily return implied by total return
                n = (t1 - t0).days
                if n > 0:
                    daily = (1.0 + bh_total) ** (1.0 / n) - 1.0
                    bh_curve = (1.0 + daily) ** (
                        (dates - t0).dt.days.values
                    )
                    ax.plot(dates, bh_curve, label="Buy & hold",
                            linewidth=2.0, color="black",
                            linestyle="--")
                    bh_cache[int(h)] = pd.DataFrame(
                        {"date": dates.values, "bh_equity": bh_curve}
                    )

        ax.axhline(1.0, color="grey", linewidth=0.8, alpha=0.5)
        ax.set_title(f"$h={h}$")
        ax.set_xlabel("OOF window (exit date)")
        ax.set_ylabel("Net equity (start = 1.0)")
        ax.grid(True, alpha=0.3)
        ax.legend(loc="best", fontsize=8)

    fig.suptitle(
        f"Leakage-safe AAPL backtest, sign strategy, cost = {cost_bps:.0f} bps "
        f"per round trip. Net equity curves vs. buy-and-hold over the "
        f"same OOF window.",
        fontsize=10, y=1.02,
    )
    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=200, bbox_inches="tight")
    plt.close(fig)
    return out_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cost-bps", type=float, default=10.0)
    parser.add_argument("--strategy", default="sign")
    args = parser.parse_args()

    out = FIGURES / "backtest_equity_curves.png"
    path = make_backtest_equity_figure(
        out, cost_bps=args.cost_bps, strategy=args.strategy,
    )
    print(f"Wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
